### ISSUE TITLE
[UI] 내가 쓴 여행지

### ISSUE THREAD

**Issue by hjh1161514** [YeoGiDa/YeoGiDa-Android#100]
## 💡 Issue

마이페이지 - 내가 쓴 여행지 UI 개발

## 📝 todo
- [x]  검색 창
- [x] 전체 화면 구성
- [x]  여행지 아이템
- [x] + 플러팅 버튼
- [x] 뒤로 가기 연결
- [x] 마이페이지에서 화면 연결
- [x] 더미데이터
