### ISSUE TITLE
[UI] 댓글 단 장소

### ISSUE THREAD

**Issue by hjh1161514** [YeoGiDa/YeoGiDa-Android#101]
## 💡 Issue

마이페이지 - 댓글 단 장소 UI

## 📝 todo
- [x]  전체 화면 구성
- [x]  댓글 단 장소 item
- [x] 뒤로 가기 연결
- [x] 마이페이지에서 연결
- [x] 더미데이터
- [x] 맨 위로 가기 구현
