### ISSUE TITLE
[NETWORK] 장소 추가 API 연결

### ISSUE THREAD

**Issue by yys7517** [YeoGiDa/YeoGiDa-Android#102]
## 💡 Issue

장소 추가 API 연결

## 📝 todo
- [x] service 
- [x] request, response data 
- [x] 장소 이미지 파일로 변환해서 MultiPart List로 전송
- [x] 장소 작성 완료 후 작성한 장소 상세로 이동
