### ISSUE TITLE
[UI] 팔로우 화면

### ISSUE THREAD

**Issue by yys7517** [YeoGiDa/YeoGiDa-Android#11]
## 💡 Issue
- 내 팔로워랑 내가 팔로잉하는 유저들을 확인할 수 있는 화면 레이아웃, 더미 데이터 뿌려보기 

## 📝 todo
- [x] 유저 아이템 레이아웃 
- [x] ViewPager + TabLayout (팔로워, 팔로잉)
- [x] 삭제 다이얼로그 레이아웃
- [x] 더미 데이터로 리스트 띄워보기 
- [x] 다이얼로그 띄워보기
