### ISSUE TITLE
[BUG] 장소 둘러보기 필터

### ISSUE THREAD

**Issue by hjh1161514** [YeoGiDa/YeoGiDa-Android#113]
## 💡 Issue

장소 둘러보기 필터 실행 시 생기는 버그 수정

## 📝 todo
- [x]  장소 상세에서 뒤로 가기 시 필터 유지
- [x] 장소 상세에서 뒤로 가기 시 태그 유지
- [x] 장소 상세에서 뒤로 가기 시 리스트 유지
