### ISSUE TITLE
[UI] 유저 상세 화면

### ISSUE THREAD

**Issue by yys7517** [YeoGiDa/YeoGiDa-Android#12]
## 💡 Issue
- 유저 클릭 시 나오는 페이지 

## 📝 todo
- [x] 전체화면 구성 
- [x] 뒤로가기 연결
- [x] 팔로우 화면에서 연결
- [x] 홈 화면에서 Best Travler 유저 상세 연결
- [x] 댓글 목록에서 유저 상세 연결
- [x] 더미 데이터
