### ISSUE TITLE
[FEAT] 푸쉬 알림

### ISSUE THREAD

**Issue by hjh1161514** [YeoGiDa/YeoGiDa-Android#125]
## 💡 Issue

푸쉬 알림에 따른 기능 구현

## 📝 todo
- [x]  알림 클릭 시 로그인 진행
- [x]  팔로우 알림 클릭 시 친구 탭으로
- [x] 좋아요 알림 시 해당 여행지 상세 = 장소 둘러보기 페이지로
- [x] 댓글 알림 시 해당 장소 상세 페이지로
- [x] 각 페이지 뒤로 가기 시 화면 로직
- [x] 알림 포그라운드 동작
