### ISSUE TITLE
[UI] 여행지 상세 부분 디자인 수정

### ISSUE THREAD

**Issue by yys7517** [YeoGiDa/YeoGiDa-Android#126]
## 💡 Issue
작성자 프로필 보여주는 부분 추가 

## 📝 todo
- [x] 데이터 바인딩 수정, ViewModel 연결
- [x] 유저 상세 페이지 연결 
- [x] 여행지 게시글 작성자 memberId 받도록 Response 데이터 수정
- [x] 작성자 프로필 이미지
- [x] 작성자 닉네임
- [x] 좋아요 버튼
