### ISSUE TITLE
[NETWORK] 유저 상세 화면 API 연결

### ISSUE THREAD

**Issue by yys7517** [YeoGiDa/YeoGiDa-Android#128]
## 💡 Issue
유저 상세 화면 통신 

## 📝 todo
- [x] memberId Path로 넘겨서 받아오기 
- [x] 유저 여행 개수, 좋아요 개수
- [x] 유저가 작성한 여행지
- [x] 작성한 여행지 지역별 칩 버튼 동적으로 추가, 필터링
- [x] 팔로우 화면에서 클릭 시 연결 및 데이터 받아오기
- [x] 유저 상세 Fragment -> Activity로 전환
- [x] 기존 내비게이션 연결 코드 수정
