### ISSUE TITLE
[FEAT] 알림 화면

### ISSUE THREAD

**Issue by hjh1161514** [YeoGiDa/YeoGiDa-Android#131]
## 💡 Issue

설정 - 알림 화면 로직

## 📝 todo
- [x]  팔로우 클릭 시 유저 상세 페이지로 이동
- [x]  댓글 클릭 시 장소 상세 페이지로 이동
- [x] 좋아요 클릭 시 여행지 상세 페이지로 이동
- [x] 각 페이지 뒤로 가기 시 플로우 자연스럽게
- [x] 알림 시간 포맷 변경
- [x] 뒤로가기
