### ISSUE TITLE
[NETWORK] 둘러보기 화면 마커 클릭 이벤트

### ISSUE THREAD

**Issue by hjh1161514** [YeoGiDa/YeoGiDa-Android#134]
## 💡 Issue

둘러보기 화면 마커 클릭 시 서버 통신

## 📝 todo
- [x]  data 
- [x]  service
- [x] 마커 클릭 시 상호명, 주소 바텀시트로
- [x] 바텀 시트에 서버 통신 데이터 나타내기 (여러 닉네임 등)
- [x] 바텀 시트 클릭 시 화면 연결하기
