### ISSUE TITLE
[NETWORK] 여행지 상세 추가된 부분 API 연결

### ISSUE THREAD

**Issue by yys7517** [YeoGiDa/YeoGiDa-Android#144]
## 💡 Issue

여행지 상세 부분 API 연결

## 📝 todo
- [x] 유저 프로필 사진
- [x] 유저 닉네임
- [x] 여행지 좋아요 여부에 따른 좋아요 버튼 처리 
- [x] 여행지 좋아요 누른 유저들 목록 
- [x] 클릭 시 ripple effect 추가
- [x] 유저 목록에서 유저 상세로 연결
- [x] 본인 프로필 클릭 시 유저 상세가 아닌 마이페이지로 이동.
