### ISSUE TITLE
[UI] 알림 설정

### ISSUE THREAD

**Issue by hjh1161514** [YeoGiDa/YeoGiDa-Android#148]
## 💡 Issue

알림을 설정하는 화면 개발

## 📝 todo
- [x]  전체 화면 구성
- [x]  switch 버튼 구성
- [x] switch 버튼 색상 변경
- [x] 알림 설정 화면 연결
