### ISSUE TITLE
[FEAT] 알림 설정

### ISSUE THREAD

**Issue by hjh1161514** [YeoGiDa/YeoGiDa-Android#149]
## 💡 Issue

알림 설정에 관련한 기능 구현

## 📝 todo
- [x]  전체 switch에 따른 각 switch 설정
- [x]  전체 switch이 off면 알림 끄기
- [x] 단일 switch이 모두 on, off이면 전체 switch 상태 변경
- [x] datastore에 상태 저장
- [x] datestore에 저장된 상태에 따라 초기 check 설정
- [x] datastore에 저장된 알림에 따라 알림 보내기
- [x] Android 13 이상에서 초기 알림 권한에 따라 알림 설정 바꾸기
- [x] 뒤로가기
