### ISSUE TITLE
[FEAT] 홈 화면 이동 

### ISSUE THREAD

**Issue by hjh1161514** [YeoGiDa/YeoGiDa-Android#164]
## 💡 Issue

홈 화면 이동 로직

## 📝 todo
- [x]  월간 best 여행지 클릭 시 해당 여행지로 이동
- [x]  팔로잉의 최근 여행지 클릭 시 해당 여행지로 이동
- [x] 이동 시 tripId 전달
