### ISSUE TITLE
[NETWORK] 여행지, 장소 삭제

### ISSUE THREAD

**Issue by hjh1161514** [YeoGiDa/YeoGiDa-Android#169]
## 💡 Issue

- 여행지, 장소 삭제 서버 연결

## 📝 todo
- [x]  service에 여행지, 장소 삭제 api 추가
- [x] 여행지 삭제 api 연결
- [x] 장소 삭제 api 연결
