### ISSUE TITLE
[FEAT] 신고

### ISSUE THREAD

**Issue by hjh1161514** [YeoGiDa/YeoGiDa-Android#177]
## 💡 Issue

신고 다이얼로그 연결 

## 📝 todo
- [x]  여행지 신고 다이얼로그 연결
- [x]  장소 신고 다이얼로그 연결
- [x] 여행지 지도로 보기 아이콘 삭제 및 바텀 시트에서 화면 연결
