### ISSUE TITLE
[UI] 홈

### ISSUE THREAD

**Issue by hjh1161514** [YeoGiDa/YeoGiDa-Android#18]
## 💡 Issue

홈 화면 구성

## 📝 todo
- [x]  여행지 item 
- [x]  traveler item
- [x] 최근 게시글 item
- [x] recycler view 구성
- [x] 전체 UI 구성
- [x] recycler view 더미 데이터 추가
