### ISSUE TITLE
[BUG] 데모 버그 수정

### ISSUE THREAD

**Issue by yys7517** [YeoGiDa/YeoGiDa-Android#183]
## 💡 Issue

데모 전 버그 수정

## 📝 todo
- [x] 여행지 상세 받아오는 서비스 함수 토큰 헤더 추가하기 
- [x] 팔로우 화면 리스트 데이터 쌓이는 버그 수정 
- [x] 여기 좋아 버그 수정
