### ISSUE TITLE
[UI] 여행지 추가

### ISSUE THREAD

**Issue by hjh1161514** [YeoGiDa/YeoGiDa-Android#20]
## 💡 Issue

여행지 둘러보기에서 플러팅버튼 클릭 시 나타나는 여행지 추가 화면

## 📝 todo
- [x]  edittext selector
- [x]  button 
- [x] 사진 추가 시 나타나는 imageView
- [x] 지역 선택에서 bottom sheet
- [x] 전체 UI 구성
