### ISSUE TITLE
[UI] 장소 상세 화면

### ISSUE THREAD

**Issue by yys7517** [YeoGiDa/YeoGiDa-Android#39]
## 💡 Issue
장소 정보를 확인할 수 있는 상세 화면

## 📝 todo
- [x] 장소명, 주소, 별점 등 여러가지 장소 정보 
- [x] 이미지 ViewPager (가로 방향) 
- [x] 댓글 목록 RecyclerView
- [x] 댓글 작성 레이아웃
