### ISSUE TITLE
[UI] 알림

### ISSUE THREAD

**Issue by hjh1161514** [YeoGiDa/YeoGiDa-Android#40]
## 💡 Issue

알림 화면 개발

## 📝 todo
- [x]  전체 화면 구성
- [x]  알림 item 
- [x] mypage 관련된 nav 생성
- [x] 알림 화면 연결
