### ISSUE TITLE
[UI] 장소 지도로 보기

### ISSUE THREAD

**Issue by hjh1161514** [YeoGiDa/YeoGiDa-Android#47]
## 💡 Issue

장소에서 지도 아이콘을 클릭했을 때 나오는 화면

## 📝 todo
- [x]  mapview
- [x]  전체 화면 구성
- [x] bottom sheet 화면
- [x] bottom sheet 연결
- [x] item 구성
- [x] data 추가
- [x] 장소 둘러보기 - 장소 지도로 보기 화면 연결
