### ISSUE TITLE
[NETWORK] 장소 지도로 보기

### ISSUE THREAD

**Issue by hjh1161514** [YeoGiDa/YeoGiDa-Android#51]
## 💡 Issue

장소 지도로 보기 통신

## 📝 todo
- [x]  service 추가
- [x] data 생성
- [x]  전체 장소 받아와서 마커로 찍기
- [x] 시작 화면을 장소의 중앙값으로 설정하기
- [x] 특정 마커를 클릭하면 해당 마커의 내용이 나타나도록 하기
