### ISSUE TITLE
[UI] 여행지 게시글 레이아웃 수정 및 정렬 바텀 시트 구현

### ISSUE THREAD

**Issue by yys7517** [YeoGiDa/YeoGiDa-Android#59]
## 💡 Issue

- 여기 좋아 화면 정렬 버튼 눌렀을 때 뜨는 정렬 바텀 시트 제작
- 기획 수정에 따른 여행지 레이아웃 수정
- 여행지 장소 목록 라디오 버튼 정렬 -> 정렬 바텀 시트로 변경

## 📝 todo
- [x] 바텀 시트 레이아웃 
- [x] 여기 좋아 화면 정렬 버튼 클릭 시 정렬 바텀 시트 뜨게 
- [x] 여행지 레이아웃 수정 및 장소 정렬 버튼 클릭 리스너 연결
