### ISSUE TITLE
[FEAT] 여행지 추가

### ISSUE THREAD

**Issue by hjh1161514** [YeoGiDa/YeoGiDa-Android#63]
## 💡 Issue

여행지 추가 관련 기능 구현

## 📝 todo
- [ ]  뒤로 가기 
- [ ]  완료 버튼 활성화
- [ ] edittext 제약
- [ ] 갤러리 연동
- [ ] 사진 클릭 시 화면에 나타나도록
- [ ] x 버튼 누르면 사진 지우기
- [ ] 사진 클릭 시 크게 보이도록
