### ISSUE TITLE
[FEAT] 장소 추가 화면 기능

### ISSUE THREAD

**Issue by yys7517** [YeoGiDa/YeoGiDa-Android#82]
## 💡 Issue
장소 추가 화면 기능 

## 📝 todo
- [x] 장소 검색 API 연결해서 장소 이름, 위도, 경도 받아오기 
- [x] 태그 값 받아오기 
- [x] 이미지 크게 보기
- [x] 선택한 이미지들 담아오기
- [x] 완료 버튼 활성화 로직
- [x] 툴바 뒤로가기 리스너 연결
- [x] 다중 선택 이미지 피커 구현
- [x] 장소 이미지 추가, 수정 창에서 x버튼 클릭하면 이미지 제거
