### ISSUE TITLE
[NETWORK] 장소 태그, 장소 정렬 

### ISSUE THREAD

**Issue by hjh1161514** [YeoGiDa/YeoGiDa-Android#91]
## 💡 Issue

장소 태그, 장소 정렬 api 연결

## 📝 todo
- [x]  정렬 api 연결
- [x] chipbutton clicklistener 연결
- [x]  태그 api 연결
