### ISSUE TITLE
[FEAT] 여행지 - 장소 간의 데이터 전달

### ISSUE THREAD

**Issue by hjh1161514** [YeoGiDa/YeoGiDa-Android#92]
## 💡 Issue

여행지에서 장소로 이동할 때 데이터 전달

## 📝 todo
- [x] safe args 플러그인 추가
- [x] argument 추가
- [x]  여행지 추가 -> place activity로 tripId 전달
- [x]  place activity -> place around fragment로 tripId 전달
- [x] 여행지 id로 여행지 정보 불러오기
